from __future__ import annotations

import argparse
from pathlib import Path

import cv2
import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run TensorRT inference exported by MMDeploy and save visualized predictions."
    )
    parser.add_argument(
        "--model-dir",
        type=Path,
        required=True,
        help="Directory generated by MMDeploy deploy.py (contains .engine and deploy.json)",
    )
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="Input image path or directory",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("runs/tensorrt_infer"),
        help="Directory to store visualized outputs",
    )
    parser.add_argument(
        "--classes",
        type=Path,
        default=Path("classes.txt"),
        help="Path to class list file (one class per line)",
    )
    parser.add_argument("--score-thr", type=float, default=0.25, help="Score threshold")
    parser.add_argument(
        "--device",
        type=str,
        default="cuda",
        help="Inference device passed to mmdeploy_runtime Detector",
    )
    return parser.parse_args()


def load_classes(path: Path) -> list[str]:
    if not path.exists():
        return []
    names = [line.strip() for line in path.read_text(encoding="utf-8").splitlines()]
    return [n for n in names if n]


def list_images(path: Path) -> list[Path]:
    if path.is_file():
        return [path]

    images: list[Path] = []
    for suffix in ("*.jpg", "*.jpeg", "*.png", "*.bmp"):
        images.extend(sorted(path.glob(suffix)))
    return images


def parse_detector_output(output: object) -> tuple[np.ndarray, np.ndarray]:
    if isinstance(output, tuple) and len(output) >= 2:
        bboxes = np.asarray(output[0])
        labels = np.asarray(output[1])
        return bboxes, labels

    if isinstance(output, dict):
        bboxes = np.asarray(output.get("dets", []))
        labels = np.asarray(output.get("labels", []))
        return bboxes, labels

    return np.empty((0, 5), dtype=np.float32), np.empty((0,), dtype=np.int64)


def draw_detections(
    image: np.ndarray,
    bboxes: np.ndarray,
    labels: np.ndarray,
    class_names: list[str],
    score_thr: float,
) -> np.ndarray:
    canvas = image.copy()
    for i, bbox in enumerate(bboxes):
        if bbox.shape[0] < 5:
            continue
        score = float(bbox[4])
        if score < score_thr:
            continue

        x1, y1, x2, y2 = [int(v) for v in bbox[:4]]
        label_id = int(labels[i]) if i < len(labels) else -1
        class_name = class_names[label_id] if 0 <= label_id < len(class_names) else str(label_id)
        caption = f"{class_name}:{score:.2f}"

        cv2.rectangle(canvas, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.putText(
            canvas,
            caption,
            (x1, max(0, y1 - 8)),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.5,
            (0, 255, 0),
            1,
            cv2.LINE_AA,
        )
    return canvas


def main() -> None:
    args = parse_args()
    model_dir = args.model_dir.resolve()
    input_path = args.input.resolve()
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    classes = load_classes(args.classes.resolve())
    images = list_images(input_path)
    if not images:
        raise FileNotFoundError(f"No images found at: {input_path}")

    try:
        from mmdeploy_runtime import Detector
    except ImportError as exc:
        raise SystemExit(
            "mmdeploy_runtime is not installed. Install mmdeploy-runtime-gpu before running inference."
        ) from exc

    detector = Detector(model_path=str(model_dir), device_name=args.device)

    for image_path in images:
        image = cv2.imread(str(image_path))
        if image is None:
            print(f"[WARN] Skip unreadable image: {image_path}")
            continue

        output = detector(str(image_path))
        bboxes, labels = parse_detector_output(output)
        vis = draw_detections(image, bboxes, labels, classes, args.score_thr)

        out_path = output_dir / image_path.name
        cv2.imwrite(str(out_path), vis)
        print(f"[OK] Saved: {out_path}")


if __name__ == "__main__":
    main()
